export const apps_array = [
    { name: "WhatsApp Messenger", package: "com.whatsapp" },
    { name: "Facebook", package: "com.facebook.katana" },
    { name: "Instagram", package: "com.instagram.android" },
    { name: "Snapchat", package: "com.snapchat.android" },
    { name: "Spotify: Music and Podcasts", package: "com.spotify.music" },
    { name: "TikTok", package: "com.zhiliaoapp.musically" },
    { name: "Google Maps", package: "com.google.android.apps.maps" },
    { name: "YouTube", package: "com.google.android.youtube" },
    { name: "Gmail", package: "com.google.android.gm" },
    { name: "Zoom - One Platform to Connect", package: "us.zoom.videomeetings" },
    { name: "Microsoft Teams", package: "com.microsoft.teams" },
    { name: "Twitter", package: "com.twitter.android" },
    { name: "Netflix", package: "com.netflix.mediaclient" },
    { name: "Amazon Shopping", package: "com.amazon.mShop.android.shopping" },
    { name: "Google Drive", package: "com.google.android.apps.docs" },
    { name: "Pinterest", package: "com.pinterest" },
    { name: "Reddit", package: "com.reddit.frontpage" },
    { name: "Adobe Acrobat Reader", package: "com.adobe.reader" },
    { name: "LinkedIn", package: "com.linkedin.android" },
    { name: "Microsoft Word", package: "com.microsoft.office.word" },
    { name: "Uber", package: "com.ubercab" },
    { name: "Airbnb", package: "com.airbnb.android" },
    { name: "Dropbox", package: "com.dropbox.android" },
    { name: "Discord", package: "com.discord" },
    { name: "Telegram", package: "org.telegram.messenger" },
    { name: "Skype", package: "com.skype.raider" },
    { name: "Google Photos", package: "com.google.android.apps.photos" },
    { name: "Google Calendar", package: "com.google.android.calendar" },
    { name: "PayPal", package: "com.paypal.android.p2pmobile" },
    { name: "Cash App", package: "com.squareup.cash" },
    { name: "Venmo", package: "com.venmo" },
    { name: "Samsung Health", package: "com.sec.android.app.shealth" },
    { name: "Google Fit", package: "com.google.android.apps.fitness" },
    { name: "Shazam", package: "com.shazam.android" },
    { name: "Waze Navigation & Live Traffic", package: "com.waze" },
    { name: "Spotify Kids", package: "com.spotify.kids" },
    { name: "SoundCloud", package: "com.soundcloud.android" },
    { name: "Clash of Clans", package: "com.supercell.clashofclans" },
    { name: "PUBG Mobile", package: "com.tencent.ig" },
    { name: "Candy Crush Saga", package: "com.king.candycrushsaga" },
    { name: "Subway Surfers", package: "com.kiloo.subwaysurf" },
    { name: "Minecraft", package: "com.mojang.minecraftpe" },
    { name: "Roblox", package: "com.roblox.client" },
    { name: "Duolingo", package: "com.duolingo" },
    { name: "Khan Academy", package: "org.khansacademy.android" },
    { name: "Coursera", package: "org.coursera.android" },
    { name: "Udemy", package: "com.udemy.android" },
    { name: "Quizlet", package: "com.quizlet.quizletandroid" },
    { name: "Google Classroom", package: "com.google.android.apps.classroom" },
    { name: "Microsoft Excel", package: "com.microsoft.office.excel" },
    { name: "Adobe Lightroom", package: "com.adobe.lrmobile" },
    { name: "Canva", package: "com.canva.editor" },
    { name: "PicsArt Photo Editor", package: "com.picsart.studio" },
    { name: "VSCO", package: "com.vsco.cam" },
    { name: "Snapseed", package: "com.niksoftware.snapseed" },
    { name: "Hulu", package: "com.hulu.plus" },
    { name: "Disney+", package: "com.disney.disneyplus" },
    { name: "HBO Max", package: "com.hbo.hbonow" },
    { name: "Peacock TV", package: "com.peacocktv.peacockandroid" },
    { name: "Paramount+", package: "com.cbs.app" },
    { name: "Crunchyroll", package: "com.crunchyroll.crunchyroid" },
    { name: "Twitch", package: "tv.twitch.android.app" },
    { name: "Yelp", package: "com.yelp.android" },
    { name: "Tripadvisor", package: "com.tripadvisor.tripadvisor" },
    { name: "Google Pay", package: "com.google.android.apps.walletnfcrel" },
    { name: "Zillow", package: "com.zillow.android.zillowmap" },
    { name: "Realtor.com", package: "com.move.realtor" },
    { name: "Robinhood", package: "com.robinhood.android" },
    { name: "Fidelity Investments", package: "com.fidelity.android" },
    { name: "TD Ameritrade", package: "com.tdameritrade.mobile3" },
    { name: "Bloomberg", package: "com.bloomberg.android.plus" },
    { name: "CNBC", package: "com.cnbc.client" },
    { name: "BBC News", package: "bbc.mobile.news.ww" },
    { name: "NYTimes", package: "com.nytimes.android" },
    { name: "The Washington Post", package: "com.washingtonpost.rainbow" },
    { name: "CNN", package: "com.cnn.mobile.android.phone" },
    { name: "Weather Channel", package: "com.weather.Weather" },
    { name: "AccuWeather", package: "com.accuweather.android" },
    { name: "MyRadar Weather Radar", package: "com.acmeaom.android.myradar" },
    { name: "Google Home", package: "com.google.android.apps.chromecast.app" },
    { name: "Ring - Always Home", package: "com.ringapp" },
    { name: "Philips Hue", package: "com.philips.lighting.hue2" },
    { name: "SmartThings", package: "com.samsung.android.oneconnect" },
    { name: "Fitbit", package: "com.fitbit.FitbitMobile" },
    { name: "Garmin Connect", package: "com.garmin.android.apps.connectmobile" },
    { name: "Strava", package: "com.strava" },
    { name: "Nike Run Club", package: "com.nike.plusgps" },
    { name: "Calm", package: "com.calm.android" },
    { name: "Headspace", package: "com.getsomeheadspace.android" },
    { name: "Sleep Cycle", package: "com.northcube.sleepcycle" },
    { name: "Bumble", package: "com.bumble.app" },
    { name: "Tinder", package: "com.tinder" },
    { name: "Hinge", package: "co.hinge.app" },
    { name: "OkCupid", package: "com.okcupid.okcupid" },
    { name: "Plenty of Fish Dating App", package: "com.pof.android" },
    { name: "eBay", package: "com.ebay.mobile" },
    { name: "Etsy", package: "com.etsy.android" },
    { name: "AliExpress", package: "com.alibaba.aliexpresshd" },
    { name: "Poshmark", package: "com.poshmark.app" },
    { name: "Mercari", package: "com.mercariapp.mercari" },
    { name: "OfferUp", package: "com.offerup" },
    { name: "Wish", package: "com.contextlogic.wish" },
    { name: "Samsung Internet Browser", package: "com.sec.android.app.sbrowser" },
    { name: "Firefox Browser", package: "org.mozilla.firefox" },
    { name: "DuckDuckGo Privacy Browser", package: "com.duckduckgo.mobile.android" },
    { name: "Opera Browser", package: "com.opera.browser" },
    { name: "Brave Private Browser", package: "com.brave.browser" },
    { name: "Bitwarden Password Manager", package: "com.x8bit.bitwarden" },
    { name: "LastPass", package: "com.lastpass.lpandroid" },
    { name: "1Password", package: "com.agilebits.onepassword" }
];